### ISSUE TITLE
XSD for 3.1

### ISSUE THREAD

**Issue by arildm** [metashare/META-SHARE#773]
Hi!

Are there any plans to create XML Schema Definition (XSD) files for the current version 3.1? There are currently XSD files for 2.0, 2.1 and 3.0 under [misc/schema](https://github.com/metashare/META-SHARE/tree/master/misc/schema)

Version 3.1 of the model is described in text in the _META-SHARE documentation report_ PDF: http://www.meta-share.org/p/93/Documentation#model

**Comment by MiltosD** [comment]
Hello arildm, 

Check here (branch metashare-3.1): https://github.com/metashare/META-SHARE/tree/metashare-3.1/misc/schema/v3.1
