### ISSUE TITLE
Cant access knowledgebase pages on meta-share.org

### ISSUE THREAD

**Issue by borsna** [metashare/META-SHARE#775]
To reproduce:

* Go to http://www.meta-share.org
* Navigate to `LEARN` -> `KNOWLEDGE BASE` 
* Get the same page and the portal landing page http://metashare.ilsp.gr/knowledgebase/homePage (also tried http://www.meta-share.org/knowledgebase/homePage with the same result)

![image](https://github.com/metashare/META-SHARE/assets/794445/bd6c1563-e1ac-4340-8500-313a0c4a889d)

**Comment by MiltosD** [comment]
Thank you for your comment. This seems have been resolved.

**Comment by borsna** [comment]
Works for me now.
Minor thing is a 404 for:  
http://www.meta-share.org/knowledgebase/theMETASHAREHierarchy 
Link in the menu `Overview of the metadata model` -> `The META-SHARE hierarchy`
Is there a replacement link?
